### ISSUE TITLE
"Unsupported parameters for (community.windows.win_domain_user) module: group_action.

### ISSUE THREAD

**Issue by dimi4ik** [andif888/azure-playground#1]
Hi @andif888 , 
The entire deployment is not fully completed and breaks here. 

`
    - name: infra-dc - Add users
      community.windows.win_domain_user:
        name: '{{ item.name }}'
        groups: '{{ item.groups }}'
        group_action: add`

TASK [infra-dc - Add users] ****************************************************
failed: [dc0] (item={'name': 'a-root', 'groups': ['IT'], 'ou_path': 'OU=it,OU=users,OU=infra,DC=playground,DC=prianto,DC=com'}) => {"ansible_loop_var": "item", "changed": false, "item": {"groups": ["IT"], "name": "a-root", "ou_path": "OU=it,OU=users,OU=infra,DC=playground,DC=prianto,DC=com"}, "msg": "Unsupported parameters for (community.windows.win_domain_user) module: group_action. Supported parameters include: password_never_expires, enabled, update_password, groups_missing_behaviour, country, spn_action, surname, sam_account_name, identity, user_cannot_change_password, firstname, password, delegates, attributes, account_locked, domain_username, groups_action, postal_code, state, city, upn, domain_server, spn, description, path, groups, company, email, domain_password, street, name, state_province, password_expired, lastname, principals_allowed_to_delegate, spns"}

Could you please check at some point or give me a tip?

 If I add "#ignore_errors: true" in the "infra-dc" playbook, it continues to run, but it breaks at another point. Thank you.

**Comment by andif888** [comment]
checking....
I think there is a typo.
